export const cards = [
    {
        id: 1,
        name: 'Шут',
        image: '/images/01.webp',
        meaning: 'Начало пути, спонтанность, невинность',
    },
    {
        id: 2,
        name: 'Маг',
        image: '/images/02.webp',
        meaning: 'Мастерство, сила воли, реализация',
    },
    {
        id: 3,
        name: 'Верховная Жрица',
        image: '/images/03.webp',
        meaning: 'Интуиция, тайна, подсознание',
    },
    {
        id: 4,
        name: 'Императрица',
        image: '/images/04.webp',
        meaning: 'Плодородие, изобилие, материнство',
    },
    {
        id: 5,
        name: 'Император',
        image: '/images/05.webp',
        meaning: 'Авторитет, структура, контроль',
    },
    {
        id: 6,
        name: 'Иерофант',
        image: '/images/06.webp',
        meaning: 'Традиции, духовность, наставничество',
    },
    {
        id: 7,
        name: 'Влюбленные',
        image: '/images/07.webp',
        meaning: 'Любовь, выбор, гармония',
    },
    {
        id: 8,
        name: 'Колесница',
        image: '/images/08.webp',
        meaning: 'Победа, движение, решительность',
    },
    {
        id: 9,
        name: 'Сила',
        image: '/images/09.webp',
        meaning: 'Мужество, внутренняя сила, терпение',
    },
    {
        id: 10,
        name: 'Отшельник',
        image: '/images/10.webp',
        meaning: 'Мудрость, уединение, поиск истины',
    },
    {
        id: 11,
        name: 'Колесо Фортуны',
        image: '/images/11.webp',
        meaning: 'Судьба, перемены, удача',
    },
    {
        id: 12,
        name: 'Справедливость',
        image: '/images/12.webp',
        meaning: 'Равновесие, истина, закон',
    },
    {
        id: 13,
        name: 'Повешенный',
        image: '/images/13.webp',
        meaning: 'Жертва, сдача, новый взгляд',
    },
    {
        id: 14,
        name: 'Смерть',
        image: '/images/14.webp',
        meaning: 'Трансформация, конец, обновление',
    },
    {
        id: 15,
        name: 'Умеренность',
        image: '/images/15.webp',
        meaning: 'Баланс, гармония, терпение',
    },
    {
        id: 16,
        name: 'Дьявол',
        image: '/images/16.webp',
        meaning: 'Зависимость, искушение, материализм',
    },
    {
        id: 17,
        name: 'Башня',
        image: '/images/17.webp',
        meaning: 'Разрушение, внезапные перемены, освобождение',
    },
    {
        id: 18,
        name: 'Звезда',
        image: '/images/18.webp',
        meaning: 'Надежда, вдохновение, исцеление',
    },
    {
        id: 19,
        name: 'Луна',
        image: '/images/19.webp',
        meaning: 'Иллюзии, страх, подсознание',
    },
    {
        id: 20,
        name: 'Солнце',
        image: '/images/20.webp',
        meaning: 'Радость, успех, ясность',
    },
    {
        id: 21,
        name: 'Суд',
        image: '/images/21.webp',
        meaning: 'Пробуждение, возрождение, решение',
    },
    {
        id: 22,
        name: 'Мир',
        image: '/images/22.webp',
        meaning: 'Завершение, гармония, цельность',
    },
    // Младшие Арканы - Жезлы
    {
        id: 23,
        name: 'Туз Жезлов',
        image: '/images/23.webp',
        meaning: 'Начало, вдохновение, потенциал',
    },
    {
        id: 24,
        name: 'Двойка Жезлов',
        image: '/images/24.webp',
        meaning: 'Планирование, выбор, амбиции',
    },
    {
        id: 25,
        name: 'Тройка Жезлов',
        image: '/images/25.webp',
        meaning: 'Расширение, прогресс, дальновидность',
    },
    {
        id: 26,
        name: 'Четверка Жезлов',
        image: '/images/26.webp',
        meaning: 'Праздник, стабильность, сообщество',
    },
    {
        id: 27,
        name: 'Пятерка Жезлов',
        image: '/images/27.webp',
        meaning: 'Конфликт, конкуренция, напряжение',
    },
    {
        id: 28,
        name: 'Шестерка Жезлов',
        image: '/images/28.webp',
        meaning: 'Победа, признание, триумф',
    },
    {
        id: 29,
        name: 'Семерка Жезлов',
        image: '/images/29.webp',
        meaning: 'Защита, стойкость, борьба',
    },
    {
        id: 30,
        name: 'Восьмерка Жезлов',
        image: '/images/30.webp',
        meaning: 'Скорость, движение, прогресс',
    },
    {
        id: 31,
        name: 'Девятка Жезлов',
        image: '/images/31.webp',
        meaning: 'Устойчивость, выносливость, границы',
    },
    {
        id: 32,
        name: 'Десятка Жезлов',
        image: '/images/32.webp',
        meaning: 'Бремя, ответственность, перегрузка',
    },
    {
        id: 33,
        name: 'Паж Жезлов',
        image: '/images/33.webp',
        meaning: 'Энтузиазм, исследование, новости',
    },
    {
        id: 34,
        name: 'Рыцарь Жезлов',
        image: '/images/34.webp',
        meaning: 'Действие, страсть, импульсивность',
    },
    {
        id: 35,
        name: 'Королева Жезлов',
        image: '/images/35.webp',
        meaning: 'Уверенность, независимость, харизма',
    },
    {
        id: 36,
        name: 'Король Жезлов',
        image: '/images/36.webp',
        meaning: 'Лидерство, видение, предпринимательство',
    },
    // Младшие Арканы - Кубки
    {
        id: 37,
        name: 'Туз Кубков',
        image: '/images/37.webp',
        meaning: 'Любовь, эмоции, новые чувства',
    },
    {
        id: 38,
        name: 'Двойка Кубков',
        image: '/images/38.webp',
        meaning: 'Партнерство, связь, гармония',
    },
    {
        id: 39,
        name: 'Тройка Кубков',
        image: '/images/39.webp',
        meaning: 'Дружба, радость, праздник',
    },
    {
        id: 40,
        name: 'Четверка Кубков',
        image: '/images/40.webp',
        meaning: 'Апатия, размышления, переоценка',
    },
    {
        id: 41,
        name: 'Пятерка Кубков',
        image: '/images/41.webp',
        meaning: 'Потеря, сожаление, печаль',
    },
    {
        id: 42,
        name: 'Шестерка Кубков',
        image: '/images/42.webp',
        meaning: 'Ностальгия, воспоминания, детство',
    },
    {
        id: 43,
        name: 'Семерка Кубков',
        image: '/images/43.webp',
        meaning: 'Выбор, иллюзии, мечты',
    },
    {
        id: 44,
        name: 'Восьмерка Кубков',
        image: '/images/44.webp',
        meaning: 'Отход, поиск, уход',
    },
    {
        id: 45,
        name: 'Девятка Кубков',
        image: '/images/45.webp',
        meaning: 'Удовлетворение, желание, счастье',
    },
    {
        id: 46,
        name: 'Десятка Кубков',
        image: '/images/46.webp',
        meaning: 'Гармония, семья, счастье',
    },
    {
        id: 47,
        name: 'Паж Кубков',
        image: '/images/47.webp',
        meaning: 'Творчество, интуиция, послание',
    },
    {
        id: 48,
        name: 'Рыцарь Кубков',
        image: '/images/48.webp',
        meaning: 'Романтика, идеализм, мечтатель',
    },
    {
        id: 49,
        name: 'Королева Кубков',
        image: '/images/49.webp',
        meaning: 'Сострадание, забота, эмоциональность',
    },
    {
        id: 50,
        name: 'Король Кубков',
        image: '/images/50.webp',
        meaning: 'Мудрость, спокойствие, контроль эмоций',
    },
    // Младшие Арканы - Мечи
    {
        id: 51,
        name: 'Туз Мечей',
        image: '/images/51.webp',
        meaning: 'Ясность, прорыв, истина',
    },
    {
        id: 52,
        name: 'Двойка Мечей',
        image: '/images/52.webp',
        meaning: 'Выбор, нерешительность, тупик',
    },
    {
        id: 53,
        name: 'Тройка Мечей',
        image: '/images/53.webp',
        meaning: 'Боль, предательство, разбитое сердце',
    },
    {
        id: 54,
        name: 'Четверка Мечей',
        image: '/images/54.webp',
        meaning: 'Отдых, восстановление, покой',
    },
    {
        id: 55,
        name: 'Пятерка Мечей',
        image: '/images/55.webp',
        meaning: 'Поражение, конфликт, напряжение',
    },
    {
        id: 56,
        name: 'Шестерка Мечей',
        image: '/images/56.webp',
        meaning: 'Переход, движение, исцеление',
    },
    {
        id: 57,
        name: 'Семерка Мечей',
        image: '/images/57.webp',
        meaning: 'Обман, стратегия, хитрость',
    },
    {
        id: 58,
        name: 'Восьмерка Мечей',
        image: '/images/58.webp',
        meaning: 'Ограничения, страх, ловушка',
    },
    {
        id: 59,
        name: 'Девятка Мечей',
        image: '/images/59.webp',
        meaning: 'Тревога, кошмары, отчаяние',
    },
    {
        id: 60,
        name: 'Десятка Мечей',
        image: '/images/60.webp',
        meaning: 'Конец, предательство, крах',
    },
    {
        id: 61,
        name: 'Паж Мечей',
        image: '/images/61.webp',
        meaning: 'Любопытство, бдительность, новости',
    },
    {
        id: 62,
        name: 'Рыцарь Мечей',
        image: '/images/62.webp',
        meaning: 'Решительность, амбиции, импульсивность',
    },
    {
        id: 63,
        name: 'Королева Мечей',
        image: '/images/63.webp',
        meaning: 'Ясность, независимость, остроумие',
    },
    {
        id: 64,
        name: 'Король Мечей',
        image: '/images/64.webp',
        meaning: 'Авторитет, логика, дисциплина',
    },
    // Младшие Арканы - Пентакли
    {
        id: 65,
        name: 'Туз Пентаклей',
        image: '/images/65.webp',
        meaning: 'Возможности, процветание, начало',
    },
    {
        id: 66,
        name: 'Двойка Пентаклей',
        image: '/images/66.webp',
        meaning: 'Баланс, адаптация, многозадачность',
    },
    {
        id: 67,
        name: 'Тройка Пентаклей',
        image: '/images/67.webp',
        meaning: 'Работа, мастерство, сотрудничество',
    },
    {
        id: 68,
        name: 'Четверка Пентаклей',
        image: '/images/68.webp',
        meaning: 'Стабильность, контроль, жадность',
    },
    {
        id: 69,
        name: 'Пятерка Пентаклей',
        image: '/images/69.webp',
        meaning: 'Потеря, бедность, изоляция',
    },
    {
        id: 70,
        name: 'Шестерка Пентаклей',
        image: '/images/70.webp',
        meaning: 'Щедрость, благотворительность, равновесие',
    },
    {
        id: 71,
        name: 'Семерка Пентаклей',
        image: '/images/71.webp',
        meaning: 'Терпение, инвестиции, рост',
    },
    {
        id: 72,
        name: 'Восьмерка Пентаклей',
        image: '/images/72.webp',
        meaning: 'Усердие, мастерство, обучение',
    },
    {
        id: 73,
        name: 'Девятка Пентаклей',
        image: '/images/73.webp',
        meaning: 'Изобилие, независимость, роскошь',
    },
    {
        id: 74,
        name: 'Десятка Пентаклей',
        image: '/images/74.webp',
        meaning: 'Наследие, семья, богатство',
    },
    {
        id: 75,
        name: 'Паж Пентаклей',
        image: '/images/75.webp',
        meaning: 'Ученичество, амбиции, возможности',
    },
    {
        id: 76,
        name: 'Рыцарь Пентаклей',
        image: '/images/76.webp',
        meaning: 'Надежность, трудолюбие, методичность',
    },
    {
        id: 77,
        name: 'Королева Пентаклей',
        image: '/images/77.webp',
        meaning: 'Практичность, забота, изобилие',
    },
    {
        id: 78,
        name: 'Король Пентаклей',
        image: '/images/78.webp',
        meaning: 'Успех, стабильность, власть',
    },
]

export default cards
