export const cards = [
    {
        id: 1,
        name: 'Шут',
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/86/RWS_Tarot_00_Fool.jpg',
        meaning: 'Начало пути, спонтанность, невинность',
    },
    {
        id: 2,
        name: 'Маг',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg',
        meaning: 'Мастерство, сила воли, реализация',
    },
    {
        id: 3,
        name: 'Верховная Жрица',
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg',
        meaning: 'Интуиция, тайна, подсознание',
    },
    {
        id: 4,
        name: 'Императрица',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg',
        meaning: 'Плодородие, изобилие, материнство',
    },
    {
        id: 5,
        name: 'Император',
        image: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg',
        meaning: 'Авторитет, структура, контроль',
    },
    {
        id: 6,
        name: 'Иерофант',
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg',
        meaning: 'Традиции, духовность, наставничество',
    },
    {
        id: 7,
        name: 'Влюбленные',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/36/RWS_Tarot_06_Lovers.jpg',
        meaning: 'Любовь, выбор, гармония',
    },
    {
        id: 8,
        name: 'Колесница',
        image: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg',
        meaning: 'Победа, движение, решительность',
    },
    {
        id: 9,
        name: 'Сила',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg',
        meaning: 'Мужество, внутренняя сила, терпение',
    },
    {
        id: 10,
        name: 'Отшельник',
        image: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg',
        meaning: 'Мудрость, уединение, поиск истины',
    },
    {
        id: 11,
        name: 'Колесо Фортуны',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg',
        meaning: 'Судьба, перемены, удача',
    },
    {
        id: 12,
        name: 'Справедливость',
        image: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg',
        meaning: 'Равновесие, истина, закон',
    },
    {
        id: 13,
        name: 'Повешенный',
        image: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg',
        meaning: 'Жертва, сдача, новый взгляд',
    },
    {
        id: 14,
        name: 'Смерть',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg',
        meaning: 'Трансформация, конец, обновление',
    },
    {
        id: 15,
        name: 'Умеренность',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/RWS_Tarot_14_Temperance.jpg',
        meaning: 'Баланс, гармония, терпение',
    },
    {
        id: 16,
        name: 'Дьявол',
        image: 'https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg',
        meaning: 'Зависимость, искушение, материализм',
    },
    {
        id: 17,
        name: 'Башня',
        image: 'https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg',
        meaning: 'Разрушение, внезапные перемены, освобождение',
    },
    {
        id: 18,
        name: 'Звезда',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg',
        meaning: 'Надежда, вдохновение, исцеление',
    },
    {
        id: 19,
        name: 'Луна',
        image: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg',
        meaning: 'Иллюзии, страх, подсознание',
    },
    {
        id: 20,
        name: 'Солнце',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_19_Sun.jpg',
        meaning: 'Радость, успех, ясность',
    },
    {
        id: 21,
        name: 'Суд',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/d6/RWS_Tarot_20_Judgement.jpg',
        meaning: 'Пробуждение, возрождение, решение',
    },
    {
        id: 22,
        name: 'Мир',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg',
        meaning: 'Завершение, гармония, цельность',
    },
    // Младшие Арканы - Жезлы
    {
        id: 23,
        name: 'Туз Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg',
        meaning: 'Начало, вдохновение, потенциал',
    },
    {
        id: 24,
        name: 'Двойка Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Wands02.jpg',
        meaning: 'Планирование, выбор, амбиции',
    },
    {
        id: 25,
        name: 'Тройка Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Wands03.jpg',
        meaning: 'Расширение, прогресс, дальновидность',
    },
    {
        id: 26,
        name: 'Четверка Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Wands04.jpg',
        meaning: 'Праздник, стабильность, сообщество',
    },
    {
        id: 27,
        name: 'Пятерка Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Wands05.jpg',
        meaning: 'Конфликт, конкуренция, напряжение',
    },
    {
        id: 28,
        name: 'Шестерка Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/5/53/Wands06.jpg',
        meaning: 'Победа, признание, триумф',
    },
    {
        id: 29,
        name: 'Семерка Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Wands07.jpg',
        meaning: 'Защита, стойкость, борьба',
    },
    {
        id: 30,
        name: 'Восьмерка Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg',
        meaning: 'Скорость, движение, прогресс',
    },
    {
        id: 31,
        name: 'Девятка Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Wands09.jpg',
        meaning: 'Устойчивость, выносливость, границы',
    },
    {
        id: 32,
        name: 'Десятка Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Wands10.jpg',
        meaning: 'Бремя, ответственность, перегрузка',
    },
    {
        id: 33,
        name: 'Паж Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Wands11.jpg',
        meaning: 'Энтузиазм, исследование, новости',
    },
    {
        id: 34,
        name: 'Рыцарь Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Wands12.jpg',
        meaning: 'Действие, страсть, импульсивность',
    },
    {
        id: 35,
        name: 'Королева Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Wands13.jpg',
        meaning: 'Уверенность, независимость, харизма',
    },
    {
        id: 36,
        name: 'Король Жезлов',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Wands14.jpg',
        meaning: 'Лидерство, видение, предпринимательство',
    },
    // Младшие Арканы - Кубки
    {
        id: 37,
        name: 'Туз Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Cups01.jpg',
        meaning: 'Любовь, эмоции, новые чувства',
    },
    {
        id: 38,
        name: 'Двойка Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Cups02.jpg',
        meaning: 'Партнерство, связь, гармония',
    },
    {
        id: 39,
        name: 'Тройка Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/7/79/Cups03.jpg',
        meaning: 'Дружба, радость, праздник',
    },
    {
        id: 40,
        name: 'Четверка Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Cups04.jpg',
        meaning: 'Апатия, размышления, переоценка',
    },
    {
        id: 41,
        name: 'Пятерка Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Cups05.jpg',
        meaning: 'Потеря, сожаление, печаль',
    },
    {
        id: 42,
        name: 'Шестерка Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Cups06.jpg',
        meaning: 'Ностальгия, воспоминания, детство',
    },
    {
        id: 43,
        name: 'Семерка Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Cups07.jpg',
        meaning: 'Выбор, иллюзии, мечты',
    },
    {
        id: 44,
        name: 'Восьмерка Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Cups08.jpg',
        meaning: 'Отход, поиск, уход',
    },
    {
        id: 45,
        name: 'Девятка Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Cups09.jpg',
        meaning: 'Удовлетворение, желание, счастье',
    },
    {
        id: 46,
        name: 'Десятка Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Cups10.jpg',
        meaning: 'Гармония, семья, счастье',
    },
    {
        id: 47,
        name: 'Паж Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Cups11.jpg',
        meaning: 'Творчество, интуиция, послание',
    },
    {
        id: 48,
        name: 'Рыцарь Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Cups12.jpg',
        meaning: 'Романтика, идеализм, мечтатель',
    },
    {
        id: 49,
        name: 'Королева Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Cups13.jpg',
        meaning: 'Сострадание, забота, эмоциональность',
    },
    {
        id: 50,
        name: 'Король Кубков',
        image: 'https://upload.wikimedia.org/wikipedia/commons/0/04/Cups14.jpg',
        meaning: 'Мудрость, спокойствие, контроль эмоций',
    },
    // Младшие Арканы - Мечи
    {
        id: 51,
        name: 'Туз Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/12/Swords01.jpg',
        meaning: 'Ясность, прорыв, истина',
    },
    {
        id: 52,
        name: 'Двойка Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Swords02.jpg',
        meaning: 'Выбор, нерешительность, тупик',
    },
    {
        id: 53,
        name: 'Тройка Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Swords03.jpg',
        meaning: 'Боль, предательство, разбитое сердце',
    },
    {
        id: 54,
        name: 'Четверка Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Swords04.jpg',
        meaning: 'Отдых, восстановление, покой',
    },
    {
        id: 55,
        name: 'Пятерка Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Swords05.jpg',
        meaning: 'Поражение, конфликт, напряжение',
    },
    {
        id: 56,
        name: 'Шестерка Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Swords06.jpg',
        meaning: 'Переход, движение, исцеление',
    },
    {
        id: 57,
        name: 'Семерка Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Swords07.jpg',
        meaning: 'Обман, стратегия, хитрость',
    },
    {
        id: 58,
        name: 'Восьмерка Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Swords08.jpg',
        meaning: 'Ограничения, страх, ловушка',
    },
    {
        id: 59,
        name: 'Девятка Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Swords09.jpg',
        meaning: 'Тревога, кошмары, отчаяние',
    },
    {
        id: 60,
        name: 'Десятка Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords10.jpg',
        meaning: 'Конец, предательство, крах',
    },
    {
        id: 61,
        name: 'Паж Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Swords11.jpg',
        meaning: 'Любопытство, бдительность, новости',
    },
    {
        id: 62,
        name: 'Рыцарь Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Swords12.jpg',
        meaning: 'Решительность, амбиции, импульсивность',
    },
    {
        id: 63,
        name: 'Королева Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords13.jpg',
        meaning: 'Ясность, независимость, остроумие',
    },
    {
        id: 64,
        name: 'Король Мечей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Swords14.jpg',
        meaning: 'Авторитет, логика, дисциплина',
    },
    // Младшие Арканы - Пентакли
    {
        id: 65,
        name: 'Туз Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Pents01.jpg',
        meaning: 'Возможности, процветание, начало',
    },
    {
        id: 66,
        name: 'Двойка Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Pents02.jpg',
        meaning: 'Баланс, адаптация, многозадачность',
    },
    {
        id: 67,
        name: 'Тройка Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Pents03.jpg',
        meaning: 'Работа, мастерство, сотрудничество',
    },
    {
        id: 68,
        name: 'Четверка Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Pents04.jpg',
        meaning: 'Стабильность, контроль, жадность',
    },
    {
        id: 69,
        name: 'Пятерка Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg',
        meaning: 'Потеря, бедность, изоляция',
    },
    {
        id: 70,
        name: 'Шестерка Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Pents06.jpg',
        meaning: 'Щедрость, благотворительность, равновесие',
    },
    {
        id: 71,
        name: 'Семерка Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Pents07.jpg',
        meaning: 'Терпение, инвестиции, рост',
    },
    {
        id: 72,
        name: 'Восьмерка Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Pents08.jpg',
        meaning: 'Усердие, мастерство, обучение',
    },
    {
        id: 73,
        name: 'Девятка Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Pents09.jpg',
        meaning: 'Изобилие, независимость, роскошь',
    },
    {
        id: 74,
        name: 'Десятка Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Pents10.jpg',
        meaning: 'Наследие, семья, богатство',
    },
    {
        id: 75,
        name: 'Паж Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Pents11.jpg',
        meaning: 'Ученичество, амбиции, возможности',
    },
    {
        id: 76,
        name: 'Рыцарь Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Pents12.jpg',
        meaning: 'Надежность, трудолюбие, методичность',
    },
    {
        id: 77,
        name: 'Королева Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Pents13.jpg',
        meaning: 'Практичность, забота, изобилие',
    },
    {
        id: 78,
        name: 'Король Пентаклей',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Pents14.jpg',
        meaning: 'Успех, стабильность, власть',
    },
]

export default cards
